# $ docker compose -f compose-www.yaml up -d

services:
  www:
    image: nginx:latest
    ports:
      - 5050:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: always
