# $ docker compose -f compose-dev.yaml up -d

services:
  dev:
    image: nginx:latest
    ports:
      - 5051:80
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: always
