services:
  www:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: always
  dev:
    image: nginx:latest
    ports:
      - 9091:80
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: always
